http://www.cityofboston.gov/copyright/privacypolicy.asp

Model.Root={DocBody}

DocBody={Head}<br><br><ol><li>{1.Sec}</li><li>{2.Sec}</li><li>{3.Sec}</li><li>{4.Sec}</li><li>{5.Sec}</li><li>{6.Sec}</li><li>{7.Sec}</li><li>{8.Sec}</li><li>{9.Sec}</li><li>{10.Sec}</li><li>{11.Sec}</li><li>{12.Sec}</li><li>{Comments.Sec}</li><li>{Liability.Sec}</li></ol>

1.Sec=<b>{1.Ti}</b><br>{1.sec}<ol><li>{1.1.Cl}</li><li>{1.2.Cl}</li><li>{1.3.Cl}</li></ol>{1.91.sec}
2.Sec=<b>{2.Ti}</b><br>{2.sec}
3.Sec=<b>{3.Ti}</b><br>{3.sec}
4.Sec=<b>{4.Ti}</b><br>{4.sec}
5.Sec=<b>{5.Ti}</b><br>{5.sec}
6.Sec=<b>{6.Ti}</b><br>{6.sec}
7.Sec=<b>{7.Ti}</b><br>{7.sec}
8.Sec=<b>{8.Ti}</b><br>{8.1.sec}<br>{8.2.sec}<br>{8.3.sec}
9.Sec=<b>{9.Ti}</b><br>{9.sec}
10.Sec=<b>{10.Ti}</b><br>{10.sec}
11.Sec=<b>{11.Ti}</b><br>{11.sec}
12.Sec=<b>{12.Ti}</b><br>{12.sec}


Head=<center><b>{Ti}</b></center><br>{0.sec}

Ti=Privacy and Security Statement

0.sec={P1.The} is committed to providing web users with convenient and secure e-government services. Thus, we are very dedicated to protecting the privacy of our visitors. This statement will explain why information is collected when you visit {P1.web.com}, hereafter referred to as 'the site,' and how that information is used and if it is shared with any third parties.

1.Ti=Data Collection

1.sec={P1.The} does collect information about visitors to the site. This information is used for analytical and statistical purposes to help better manage the site. Information that is collected includes:

1.1.Cl=The type of browser (for example: Internet Explorer, Firefox, Safari) used and the operating system on a user's computer;

1.2.Cl=The date and time a user visited the site; and

1.3.Cl=The web pages accessed at the site, as well as any applications used and forms data.

1.91.sec=We use this information to learn how many visitors we have, where they are coming from, which parts of our website are of most interest to users and other facts that will help us improve the website and the services we offer. In order to accomplish these goals, the City regularly conducts statistical analysis of the data it collects.

2.Ti=Use of Cookies

2.sec={P1.The} uses cookies that are pieces of information generated by our web server and stored on the end user's computer for future access. The City does not store any user's personal identifying information (such as name, address etc.) but keeps track of actions taken on the site such as whether the restaurant disclaimer has been read in the Mayor's Food Court application. This helps us to avoid presenting repetitive information to users before they access the various e-information applications on City's website. We believe that this use of cookies does not compromise a user's privacy and security. At any time, users have the capability to turn off the cookies using their browser settings.

3.Ti=Sending of E-mail

3.sec=If you send us an electronic mail message, either through your mail program or by using one of the online contact forms, we will only use the personally identifying information to respond to the request. We may direct your message to another government agency that can help in fulfilling your request. This personally identifying information will not be shared with any third party or other governmental agencies not directly handling your request.

4.Ti=Online Transactions

4.sec=Every effort is made to protect any sensitive personal information you give online. The site uses a secure server for conducting online financial transactions. All credit cards and other payment information that you transmit will be protected by encryption technology, provided that your browser is properly configured and your computer is operating properly. The encrypted information is shared only with our bank and a credit card clearinghouse, both of which also operate secured servers. Access to these records is limited to a very small number of employees who need it in order to perform a specific job.

5.Ti=E-Newsletters

5.sec=The City offers several e-newsletters to inform users about City initiatives, programs and events. These are "opt-in" newsletters, meaning that users must indicate their interest by signing up for the e-newsletter and providing their e-mail addresses. Should any user wish to be "unsubscribed" at any time, this option is sent out at the bottom of each newsletter. As additional newsletters may be established, all will be operated on an "opt-in" policy. Invitations to join the newsletters may be generated from e-mails sent to the City.

6.Ti=SMS (Text) Messages

6.sec={P1.The} may periodically offer SMS alerts. By signing up to receive these alerts, subscribers acknowledge that SMS message charges may apply depending on their individual mobile carrier and plan.

7.Ti=Sale of Data from the Web Site

7.sec=The City will not rent, sell or give away any personally identifying information entered into the site (name, address, phone number, etc.) to third parties for marketing or mailing list purposes without your permission. We will also not disclose credit card information, except for purposes related to your transaction or as required by law.

8.Ti=Endorsements, Links & Disclosure to Third Parties

8.1.sec=In the best interest of the constituent, content on the site is designed chiefly to provide information and help fulfill service requests. 

8.2.sec=Any inclusion of third-party hyperlinks, images, applications, or references on the site does not constitute an endorsement or recommendation by {P1.the}. Their inclusion is simply to provide users with relevant information and resources.

8.3.sec=As a governmental agency, the {P1.PublicRecordsLaws.withCitation} governs our activities. Any information received through use of the site is subject to the same provisions as information provided on paper. Otherwise we do not share any personally identifying information with any third party. For a more complete discussion of the implications of the {P1.PublicRecordsLaw.Handle}, please refer to {P1.PublicRecords.Link} that include FAQs as well as the text of the statute.

9.Ti=Children

9.sec={P1.Youth.com} is an adjunct site to the site and attracts many young users due to its ability to provide information about youth services and programs. It also publishes web content from {P1.City} youth in approved after-school or summer programs. This site in its entirety conforms to the Children's Online Privacy and Protection Act (COPPA) of 1998. In an effort to reach our youth constituency, users can become members of the site that entitles them to receive e-mail and early notification of events or programs of interest to them. There are no message boards, chat rooms or the ability for youth to interact with each other. The membership will only be used to inform users of events, programs and activities of interest to them. In addition, all the privacy protections provided under the {P1.web.com} apply to the {P1.Youth.com} site.

10.Ti=Security

10.sec=For site security purposes and to ensure that this service remains available to all users, the City employs commercial software designed to monitor network traffic to identify unauthorized attempts to upload or change information, or otherwise cause damage. Unauthorized attempts to upload information or change information on this service are strictly prohibited and may be punishable by law.

11.Ti=Intellectual Property

11.sec=Content on the site, including the City Seal, images, and graphics, is copyrighted either by {P1.the} or by a third-party provider. Any third party images, graphics, or content on the site is used with permission from the copyright holder. Before reproducing or otherwise using any content from the site, including images and graphics, users must obtain permission from the appropriate copyright holder.

12.Ti=Contact

12.sec=If you have any questions regarding our privacy policy and security, please contact the {P1.Webmaster.Link}.

Comments.Sec=<b>{Comments.Ti}</b><br>{Comments.sec}

Comments.Ti=Annotation of or Comments on This Policy

Comments.sec=Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?

Liability.Sec=<b>{Liability.Ti}</b><br>{Liability.sec}

Liability.Ti=Liability and Disclaimers

Liability.sec=At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Spaceflights cannot be stopped. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.
